users/urls.py
from django.urls import path
from users.views import UsersView, StudyGroupView
app_name = 'users'

urlpatterns = [
    path('students', UsersView.as_view(), name='list'),
    path('groups', StudyGroupView.as_view(), name='groups'),
]

exercises/models.py
from django.db import models
from django.utils.translation import gettext as _


class Exercise(models.Model):
    title = models.CharField(_('title'), max_length=512)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = _('exercise')
        verbose_name_plural = _('exercises')


class Mark(models.Model):
    exercise = models.ForeignKey(Exercise, on_delete=models.CASCADE, verbose_name=_('exercise'))
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE, related_name='user')
    user_role = models.CharField(_('role'), max_length=128)
    date = models.DateTimeField(_('date'))
    value = models.PositiveIntegerField(_('mark'))
    comment = models.TextField(_('comment'), blank=True, null=True)

    def __str__(self):
        return f'{self.exercise.title}: {self.user.last_name} {self.user.first_name}'

    class Meta:
        verbose_name = _('mark')
        verbose_name_plural = _('marks')

users/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.translation import gettext as _


class StudyGroup(models.Model):
    name = models.CharField(_('name'), max_length=512)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('study group')
        verbose_name_plural = _('study groups')
        db_table = 'users__studygroup'


class StudyProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    rank = models.CharField(_('rank'), max_length=512, blank=True, null=True)
    studygroup = models.ForeignKey(StudyGroup, on_delete=models.CASCADE, related_name='group', blank=True, null=True)

    class Meta:
        verbose_name = _('study profile')
        verbose_name_plural = _('study profiles')
        db_table = 'users__studyprofile'


@receiver(post_save, sender=User)
def create_study_profile(sender, instance, created, **kwargs):
    if created:
        StudyProfile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_study_profile(sender, instance, **kwargs):
    instance.studyprofile.save()

exercises/api/views.py
import json
from datetime import datetime as dt

from django.contrib.auth.models import User
from rest_framework.parsers import MultiPartParser, FileUploadParser
from rest_framework.response import Response
from rest_framework.views import APIView

from exercises.api.authentication import CsrfExemptSessionAuthentication
from exercises.models import Exercise, Mark


class Import(APIView):
    authentication_classes = (CsrfExemptSessionAuthentication,)
    parser_classes = (MultiPartParser, FileUploadParser)

    def post(self, request):
        print("META from request")
        print(request.META.items())
        print('Import JSON Files!')
        json_file = request.data.get('file')
        if not json_file:
            print('server did not receive file')
            return Response({'message': 'server did not receive file'}, status=400)

        json_data = json.loads(json_file.read())

        trainings = json_data.get('trainings')
        if not trainings:
            print('There are no training in file')
            return Response({'message': 'There are no training in file'}, status=400)

        for training in trainings:
            training_id = training.get('training_id')
            if not training_id:
                print('training_id is missed')
                Response({'message': 'training_id is missed'}, status=400)

            training_title = training.get('training_title')
            if not training_title:
                print('training_title is missed')
                Response({'message': 'training_title is missed'}, status=400)

            training_date = training.get('training_date')
            if not training_date:
                print('training_date is missed')
                Response({'message': 'training_date is missed'}, status=400)
            training_date = dt.utcfromtimestamp(training_date)

            user_id = training.get('user_id')
            if not user_id:
                print('user_id is missed')
                Response({'message': 'user_id is missed'}, status=400)

            user_mark = training.get('user_mark')
            if not user_mark:
                print('user_mark is missed')
                Response({'message': 'user_mark is missed'}, status=400)

            user_role = training.get('user_role', '-')
            comment = training.get('comment', '-')

            exercise, e_created = Exercise.objects.get_or_create(id=training_id, defaults={'title': training_title})

            user = User.objects.filter(id=user_id).first()
            if not user:
                print(f'There is not student with {user_id} id')
                return Response({'message': f'There is not student with {user_id} id'}, status=400)

            mark, m_created = Mark.objects.update_or_create(exercise=exercise,
                                                            user=user,
                                                            user_role= user_role,
                                                            defaults={
                                                                'value': user_mark,
                                                                'date': training_date,
                                                                'comment': comment
                                                            }
                                                            )

        data = {'starts': True}
        return Response(data, status=200, content_type='application/json')

exercises/views.py
from django.shortcuts import render
from django.views import View

from exercises.models import Mark

from exercises.core.func import send_udp_datagram


class ImportBase(View):
    template = None
    page_title = None

    def get(self, request):
        return render(request, self.template, {'page_title': self.page_title})


class ImportData(ImportBase):
    template = 'import.html'
    page_title = 'Test import'


class ImportRequest(ImportBase):
    template = 'import-request.html'
    page_title = 'Request import'

    def post(self, request):
        context = {'page_title': self.page_title}

        header_ip = request.POST.get('header_ip')
        header_port = request.POST.get('header_port')
        if not (header_ip and header_port):
            context['message'] = 'header_ip or header_port is missing'
            return render(request, self.template, context)

        header_port = int(header_port)

        send_udp_datagram(header_ip, header_port)
        context['message'] = 'UDP datagram was sent'
        return render(request, self.template, context)


class Index(ImportBase):
    template = 'index.html'
    page_title = 'Программный иммитатор КОС-УД'


class ExercisesTable(View):

    def get(self, request):
        context = {
            'page_title': 'Таблица результатов',
            'items': Mark.objects.all().order_by('-date').values('exercise__title', 'value', 'date',
                                                                'user_role', 'user__studyprofile__rank',
                                                                'user__studyprofile__studygroup__name',
                                                                'user__first_name', 'user__last_name')
        }
        return render(request, 'exercises-table.html', context)

users/api/views.py
from django.contrib.auth.models import User
from rest_framework.response import Response
from rest_framework.views import APIView

from users.api.serializers import SerializerStudyGroup, SerializerUser
from users.models import StudyGroup


class Export(APIView):

    def get(self, request):
        students = User.objects.filter(is_staff=False, is_superuser=False, is_active=True)
        students = students.select_related('studyprofile')
        students_ids = students.values_list('id', flat=True)
        groups = StudyGroup.objects.filter(group__user__in=students_ids).distinct('id')
        data = {
          "students": SerializerUser(students, many=True).data,
          "groups": SerializerStudyGroup(groups, many=True).data
        }
        return Response(data, status=200)

users/views.py
from django.shortcuts import render
from django.views import View

from users.models import StudyGroup
from django.contrib.auth.models import User

class UsersView(View):

    def get(self, request):
        context = {
            'page_title': 'Личный состав',
            'users': User.objects.exclude(is_staff=True, is_superuser=True).select_related('studyprofile')
        }
        return render(request, 'user-table.html', context)

class StudyGroupView(View):

    def get(self, request):
        context = {
            'page_title': 'Подразделения',
            'studygroups': StudyGroup.objects.all()
        }
        return render(request, 'group-table.html', context)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="robots" content="noindex">
    <title>{{ page_title }} | KOS imitator |</title>
    <link rel="stylesheet" type="text/css" href="{% static 'Roboto/roboto.css' %}">
    <style>
        *{margin:0; padding:0}

        a{
            color:#417690;
            text-decoration: none;
        }

        a:hover{
            text-decoration: underline;
        }

        html{
            font-family: "Roboto","Lucida Grande","DejaVu Sans","Bitstream Vera Sans",Verdana,Arial,sans-serif;
        }

        body{
            height: 100vh;
            display: flex;
            flex-direction: column;
        }

        header{
            width: auto;
            height: auto;
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 10px 40px;
            background: #417690;
            color: #ffc;
            overflow: hidden;
        }

        header ul{
            list-style-type: none;
            display: flex;
            padding: 0;
            margin: 0;
        }

        header ul li{
            padding: 0 .5rem;
            margin: 0;
        }

        header ul li a{
            font-size: 11px;
            text-transform: uppercase;
            color: #ffc;
            text-decoration: none;
        }

        main{
            padding: 2rem;
            flex-grow: 1;
            display:flex;
            justify-content: center;
            align-items: flex-start;
        }

        h1{
            padding: 0;
            margin: 0 20px 0 0;
            font-weight: 300;
            font-size: 24px;
            color: #f5dd5d;
        }

        form > p{
            text-align: center;
            margin-bottom: 1rem;
        }

        table{
            width:100%;
            max-width: 90vw;
            border-collapse: collapse;
        }

        th,
        td{
            padding: .5rem 1rem;
            border: 1px solid #444;
        }

        tr:nth-child(even){
            background-color: #eee;
        }

        ul{
            list-style-type: none;
        }

        li{
            padding: 0 1rem;
            margin-bottom: 1rem;
        }

        ul p{
            padding-top: .5rem;
            margin-bottom: 1rem;
        }

        main ul{
            list-style-type: square;
            padding-left:1rem;
        }

    </style>
</head>
<body>
    <header>
        <h1>{{ page_title }}</h1>

        <ul>
            <li><a href="{% url 'users:list' %}">Личный состав</a></li>
            <li><a href="{% url 'users:groups' %}">Подразделения</a></li>
            <li><a href="{% url 'exercises' %}">Таблица результатов</a></li>
            <li><a href="/moodle/">Редактирование данных</a></li>
        </ul>
    </header>
    <main>
        {% block main %}{% endblock %}
    </main>
    <footer></footer>
</body>
{% block scripts %}{% endblock %}
</html>

templates/exercises-table.html
{% extends 'base.html' %}

{% block main %}
<table>
    <tr>
        <th>Упражнение</th>
        <th>Подразделение</th>
        <th>Фамилия, имя, отчество</th>
        <th>Звание</th>
        <th>Роль</th>
        <th>Оценка</th>
        <th>Дата</th>
    </tr>
    {% for item in items %}
    <tr>
        <td>{{ item.exercise__title }}</td>
        <td>{{ item.user__studyprofile__studygroup__name }}</td>
        <td>{{ item.user__last_name }} {{ item.user__first_name }}</td>
        <td>{{ item.user__studyprofile__rank }}</td>
        <td>{{ item.user_role }}</td>
        <td>{{ item.value }}</td>
        <td>{{ item.date|date:"d.m.Y H:i" }}</td>
    </tr>
    {% endfor %}
</table>
{% endblock %}

{% block scripts %}
{% endblock %}

templates/group-table.html
{% extends 'base.html' %}

{% block main %}
<table>
    <tr>
        <th>Наименование</th>
    </tr>
    {% for group in studygroups %}
    <tr>
        <td>{{ group.name }}</td>
    </tr>
    {% endfor %}
</table>
{% endblock %}

{% block scripts %}
{% endblock %}

templates/import-request.html
{% extends 'base.html' %}

{% block main %}
        <form method="POST">
            <p>{{ message }}</p>
            {% csrf_token %}
            <input type="text" name="header_ip" placeholder="192.168.0.2">
            <input type="number" name="header_port" placeholder="6543">
            <input type="submit" value="Request data.json from Header">
        </form>
{% endblock %}

templates/import.html
{% extends 'base.html' %}

{% block main %}
        <form onsubmit="return sendFile(event);">
            <input type="file" name="file">
            <input type="submit">
        </form>
{% endblock %}

{% block scripts %}
<script>
    async function sendFile(event){
        console.log(event.target);
        event.preventDefault();
        let data = new FormData(event.target);
        let query = await fetch("{% url 'import' %}", {
            method: 'POST',
            body: data
          }).then(function (response){
            return response.json();
        }).catch(function ( error ){
            console.log(error);
        });
    }
</script>
{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block main %}
<ul>
    <p><b>Меню:</b></p>
    <li><a href="{% url 'users:list' %}">Личный состав</a></li>
    <li><a href="{% url 'users:groups' %}">Подразделения</a></li>
    <li><a href="{% url 'exercises' %}">Таблица результатов</a></li>
    <p><b>Администрирование:</b></p>
    <li><a href="/moodle/">Редактирование данных</a></li>
    <li><a href="/moodle/auth/user/add/">Добавить обучаемого</a></li>
    <li><a href="/moodle/users/studygroup/add/">Добавить подразделение</a></li>
<!--    <li><a href="{% url 'export' %}">{% url 'export' %}</a></li>-->
<!--    <li><a href="{% url 'import' %}">{% url 'import' %}</a></li>-->
<!--    <p><b>Запрос данных у Header</b></p>-->
<!--    <li><a href="{% url 'import-request' %}">Header</a></li>-->
</ul>
{% endblock %}

templates/user-table.html
{% extends 'base.html' %}

{% block main %}
<table>
    <tr>
        <th>Звание</th>
        <th>Фамилия, имя, отчество</th>
        <th>Подразделение</th>
    </tr>
    {% for user in users %}
    <tr>
        <td>{{ user.studyprofile.rank }}</td>
        <td>{{ user.last_name }} {{ user.first_name }}</td>
        <td>{{ user.studyprofile.studygroup.name }}</td>
    </tr>
    {% endfor %}
</table>
{% endblock %}

{% block scripts %}
{% endblock %}